@startuml
title Warm House Company Context Diagram

top to bottom direction

!include C4_Context.puml

Person(user, "User", "A user of smart devices")
System(FitLifeSystem, "Warm House System", "Device management, data monitoring from devices, device addition")

System_Ext(api, "Devices", "Smart home devices")

Rel(user, FitLifeSystem, "Uses the system")
Rel(FitLifeSystem,api,"Fetches device data")

@enduml