@startuml
title Warm House Company Context Diagram

top to bottom direction

!include C4_Container.puml

Person(user, "User", "A user of smart devices")
System(WarmHouseSystem, "Warm House System", "System managing and monitoring devices")

Container_Boundary(WarmHouseSystem, "Warm House System") {
  Container(APIApp, "API Application", "Go", "Handles user interactions")
  Container(MobileApp, "Mobile Application", "Kotlin, Swift", "Allows users to manage their membership")
  Container(DevicesManagementService, "Devices Management Service", "Go", "Add and manage devices")
  Container(UserInfoService, "User Info Service", "Go", "Manage user info")
  Container(DevicesMonitoringService, "Devices Monitoring Service", "Go", "Monitor device's info")
  ContainerDb(Database, "Database", "PostgreSQL", "Stores user and device data")
}

System_Ext(api, "Devices", "Smart home devices")

Rel(user, MobileApp, "Uses the system")
Rel(MobileApp, APIApp, "Execute user's actions and provide device data")

Rel(APIApp,DevicesManagementService,"Processes management requests")
Rel(APIApp,DevicesMonitoringService,"Processes monitoring requests")
Rel(APIApp,UserInfoService,"Processes user info requests")
Rel(UserInfoService,Database,"Reads/Writes user data")
Rel(DevicesManagementService,Database,"Reads/Writes device state")
Rel(DevicesMonitoringService,Database,"Reads/Writes device data")
Rel(DevicesMonitoringService,api,"Fetches device data")
Rel(DevicesManagementService,api,"Change device state")
@enduml

Создание нового пользователя
Получение телеметрии с устройства
Отправка команды устройству
